### ISSUE TITLE
dont work for redmine 4.1.0-8

### ISSUE THREAD

**Issue by faridskyman** [a1comms/redmine-google-iap-authentication#1]
i git clone in plugin, install bundle, then restart redmine, then redmine threw error
deleting folder resolves..

can fix?

**Comment by iamacarpet** [comment]
Hello @faridskyman ,

I've just tested this against the latest Redmine 5.0.3 from DockerHub and it is now working.

**Comment by faridskyman** [comment]
ok will try again, thx for the update
